/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAjustesRouteImport } from './routes/_app.ajustes'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppCheckinRouteImport } from './routes/_app.checkin'
import { Route as AppCicloRouteImport } from './routes/_app.ciclo'
import { Route as AppCitasRouteImport } from './routes/_app.citas'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppNosotrosRouteImport } from './routes/_app.nosotros'
import { Route as AppParejaRouteImport } from './routes/_app.pareja'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPreguntaRouteImport } from './routes/_app.pregunta'
import { Route as AppUbicacionRouteImport } from './routes/_app.ubicacion'
import { Route as AppEspacioKindRouteImport } from './routes/_app.espacio.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppCicloRoute = AppCicloRouteImport.update({
  id: '/ciclo',
  path: '/ciclo',
  getParentRoute: () => AppRoute,
} as any)
const AppCitasRoute = AppCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppNosotrosRoute = AppNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => AppRoute,
} as any)
const AppParejaRoute = AppParejaRouteImport.update({
  id: '/pareja',
  path: '/pareja',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPreguntaRoute = AppPreguntaRouteImport.update({
  id: '/pregunta',
  path: '/pregunta',
  getParentRoute: () => AppRoute,
} as any)
const AppUbicacionRoute = AppUbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => AppRoute,
} as any)
const AppEspacioKindRoute = AppEspacioKindRouteImport.update({
  id: '/espacio/$kind',
  path: '/espacio/$kind',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AppAjustesRoute
  '/calendario': typeof AppCalendarioRoute
  '/checkin': typeof AppCheckinRoute
  '/ciclo': typeof AppCicloRoute
  '/citas': typeof AppCitasRoute
  '/inicio': typeof AppInicioRoute
  '/nosotros': typeof AppNosotrosRoute
  '/pareja': typeof AppParejaRoute
  '/perfil': typeof AppPerfilRoute
  '/pregunta': typeof AppPreguntaRoute
  '/ubicacion': typeof AppUbicacionRoute
  '/espacio/$kind': typeof AppEspacioKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AppAjustesRoute
  '/calendario': typeof AppCalendarioRoute
  '/checkin': typeof AppCheckinRoute
  '/ciclo': typeof AppCicloRoute
  '/citas': typeof AppCitasRoute
  '/inicio': typeof AppInicioRoute
  '/nosotros': typeof AppNosotrosRoute
  '/pareja': typeof AppParejaRoute
  '/perfil': typeof AppPerfilRoute
  '/pregunta': typeof AppPreguntaRoute
  '/ubicacion': typeof AppUbicacionRoute
  '/espacio/$kind': typeof AppEspacioKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ajustes': typeof AppAjustesRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/ciclo': typeof AppCicloRoute
  '/_app/citas': typeof AppCitasRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/nosotros': typeof AppNosotrosRoute
  '/_app/pareja': typeof AppParejaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pregunta': typeof AppPreguntaRoute
  '/_app/ubicacion': typeof AppUbicacionRoute
  '/_app/espacio/$kind': typeof AppEspacioKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/checkin'
    | '/ciclo'
    | '/citas'
    | '/inicio'
    | '/nosotros'
    | '/pareja'
    | '/perfil'
    | '/pregunta'
    | '/ubicacion'
    | '/espacio/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/checkin'
    | '/ciclo'
    | '/citas'
    | '/inicio'
    | '/nosotros'
    | '/pareja'
    | '/perfil'
    | '/pregunta'
    | '/ubicacion'
    | '/espacio/$kind'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ajustes'
    | '/_app/calendario'
    | '/_app/checkin'
    | '/_app/ciclo'
    | '/_app/citas'
    | '/_app/inicio'
    | '/_app/nosotros'
    | '/_app/pareja'
    | '/_app/perfil'
    | '/_app/pregunta'
    | '/_app/ubicacion'
    | '/_app/espacio/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ciclo': {
      id: '/_app/ciclo'
      path: '/ciclo'
      fullPath: '/ciclo'
      preLoaderRoute: typeof AppCicloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citas': {
      id: '/_app/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AppCitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nosotros': {
      id: '/_app/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof AppNosotrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pareja': {
      id: '/_app/pareja'
      path: '/pareja'
      fullPath: '/pareja'
      preLoaderRoute: typeof AppParejaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pregunta': {
      id: '/_app/pregunta'
      path: '/pregunta'
      fullPath: '/pregunta'
      preLoaderRoute: typeof AppPreguntaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ubicacion': {
      id: '/_app/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof AppUbicacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/espacio/$kind': {
      id: '/_app/espacio/$kind'
      path: '/espacio/$kind'
      fullPath: '/espacio/$kind'
      preLoaderRoute: typeof AppEspacioKindRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppCicloRoute: typeof AppCicloRoute
  AppCitasRoute: typeof AppCitasRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNosotrosRoute: typeof AppNosotrosRoute
  AppParejaRoute: typeof AppParejaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPreguntaRoute: typeof AppPreguntaRoute
  AppUbicacionRoute: typeof AppUbicacionRoute
  AppEspacioKindRoute: typeof AppEspacioKindRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppCicloRoute: AppCicloRoute,
  AppCitasRoute: AppCitasRoute,
  AppInicioRoute: AppInicioRoute,
  AppNosotrosRoute: AppNosotrosRoute,
  AppParejaRoute: AppParejaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPreguntaRoute: AppPreguntaRoute,
  AppUbicacionRoute: AppUbicacionRoute,
  AppEspacioKindRoute: AppEspacioKindRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
